import { ProgressStatus } from '../constants';

const curatedWorks = {
  meta: {
    name: 'curatedWorks',
    displayName: 'Curated Archive Works',
    about: '',
    detailedDescription: 'Selected works from the archive. (Updated regularly starting 2026)',
    imageFolderName: 'curated-works',
    progressStatus: ProgressStatus.IN_PROGRESS,
    numberOfImages: 0,
    status: '',
    releaseStatus: '',
    releaseDate: '2010 - 9999',
    link: 'https://www.instagram.com/gr.xng/',
    linkDescription: '👁️‍🗨️@gr.xng',
  },
  showings: [
    // {
    //   fileName: '',
    //   displayName: '',
    //   description: '',
    //   date: '',
    // },
    {
      fileName: 'ma.jpg',
      displayName: '',
      description: '',
      date: '2014',
    },
    {
      fileName: 'people-and-lighthouse.jpg',
      displayName: 'People and Lighthouse',
      description: '',
      date: 'October 2023',
    },
    {
      fileName: 'intermission-3x2.jpg',
      displayName: 'Intermission',
      description: '',
      date: 'December 2025',
    },
    {
      fileName: 'city-bird.jpg',
      displayName: '',
      description: '',
      date: 'December 2025',
    },
    {
      fileName: 'pre-halloween-2025.jpg',
      displayName: '',
      description: '',
      date: 'October 2025',
    },
    {
      fileName: 'child\'s-play.jpg',
      displayName: 'Child\'s Play',
      description: '',
      date: 'December 2025',
    },
    {
      fileName: 'field-day-1.jpg',
      displayName: 'Field Day',
      description: '',
      date: 'December 2025',
    },
    {
      fileName: 'herder.jpg',
      displayName: 'Herder',
      description: '',
      date: 'December 2025',
    },
    {
      fileName: 'chrismas-2025.jpg',
      displayName: 'Christmas 2025',
      description: '',
      date: 'December 2025',
    },
    {
      fileName: 'winter-land.jpg',
      displayName: 'Winter Land',
      description: '',
      date: 'December 2025',
    },
    {
      fileName: 'winter-in-calvert-vaux-park.jpg',
      displayName: 'Winter in Calvert Vaux Park',
      description: '',
      date: 'December 2025',
    },
    {
      fileName: 'winter-in-calvert-vaux-park-2.jpg',
      displayName: 'Winter in Calvert Vaux Park',
      description: '',
      date: 'December 2025',
    },
    {
      fileName: 'color-study.jpg',
      displayName: 'Color Study',
      description: '',
      date: 'February 2026',
    },
    {
      fileName: 'urban-abstraction.jpg',
      displayName: 'Urban Abstraction',
      description: '',
      date: '',
    },
    {
      fileName: 'end-of-2025.jpg',
      displayName: 'End of 2025',
      description: '',
      date: '',
    },
    {
      fileName: 'beginning-of-2026.jpg',
      displayName: 'Beginning of 2026',
      description: '',
      date: 'January 2026',
    },
    {
      fileName: 'beginning-of-2026-1.jpg',
      displayName: 'Beginning of 2026',
      description: '',
      date: 'January 2026',
    },
    {
      fileName: 'wind-surfers.jpg',
      displayName: 'Wind Surfers',
      description: '',
      date: 'November 2025',
    },
    {
      fileName: 'early-morning-in-late-october.jpg',
      displayName: '',
      description: '',
      date: 'October 22nd, 2015',
    },
    {
      fileName: 'red-hook-red.jpg',
      displayName: '',
      description: '',
      date: '',
    },
    {
      fileName: 'red-hook-green.jpg',
      displayName: '',
      description: '',
      date: '',
    },
    {
      fileName: 'red-hook-water.jpg',
      displayName: '',
      description: '',
      date: '',
    },
    {
      fileName: 'mcdonals.jpg',
      displayName: '',
      description: '',
      date: '',
    },
    {
      fileName: 'fare-required.jpg',
      displayName: '',
      description: '',
      date: '',
    },
    {
      fileName: 'in-between-winter-and-spring.jpg',
      displayName: 'In Between Winter and Spring',
      description: '',
      date: '',
    },
    {
      fileName: 'in-between-winter-and-spring-2.jpg',
      displayName: 'In Between Winter and Spring',
      description: '',
      date: '',
    },
    {
      fileName: 'pinched.jpg',
      displayName: '',
      description: '',
      date: '',
    },
    {
      fileName: 'study-of-line.jpg',
      displayName: 'Line Study',
      description: '',
      date: 'November 2025',
    },
    {
      fileName: 'study-of-line-2.jpg',
      displayName: 'Line Study',
      description: '',
      date: 'November 2025',
    },
    {
      fileName: 'fish-head.jpg',
      displayName: '',
      description: '',
      date: 'December 2025',
    },
    {
      fileName: 'painting-study-1.jpg',
      displayName: 'Photo Painting Study',
      description: '',
      date: '',
    },
    {
      fileName: 'painting-study-2.jpg',
      displayName: 'Photo Painting Study',
      description: '',
      date: '',
    },
    {
      fileName: 'painting-study-3.jpg',
      displayName: 'Photo Painting Study',
      description: '',
      date: 'December 2025',
    },
    {
      fileName: 'liminal-2.jpg',
      displayName: '',
      description: '',
      date: '',
    },
    {
      fileName: 'curiousity-o-playfulness.jpg',
      displayName: '',
      description: '',
      date: '',
    },
    {
      fileName: 'afternoon-stroll-with-company.jpg',
      displayName: 'Afternoon Stroll with Company',
      description: '',
      date: '',
    },
    {
      fileName: 'preyed.jpg',
      displayName: '',
      description: '',
      date: '',
    },
    {
      fileName: 'foot-prints-in-the-sand.jpg',
      displayName: 'Footprints in the Sand',
      description: '',
      date: '',
    },
    {
      fileName: 'winter-stock.jpg',
      displayName: 'Winter Stock',
      description: '',
      date: '',
    },
    {
      fileName: 'abandoned.jpg',
      displayName: 'Abandoned',
      description: '',
      date: '',
    },
    {
      fileName: 'accompany.jpg',
      displayName: 'Accompany',
      description: '',
      date: '',
    },
    {
      fileName: 'before-rainstorm-by-the-harbor.jpg',
      displayName: 'Before Rainstorm by the Harbor',
      description: '',
      date: '',
    },
    {
      fileName: 'beginning-of-2026-2.jpg',
      displayName: 'Beginning of 2026',
      description: '',
      date: '',
    },
    {
      fileName: 'beginning-of-2026-3.jpg',
      displayName: 'Beginning of 2026',
      description: '',
      date: '',
    },
    {
      fileName: 'brooklyn-bridge.jpg',
      displayName: 'Brooklyn Bridge',
      description: '',
      date: 'April 2024',
    },
    {
      fileName: 'bushuzhike.jpg',
      displayName: '不速之客',
      description: '',
      date: '',
    },
    {
      fileName: 'cajianerguo.jpg',
      displayName: '',
      description: '',
      date: '',
    },
    {
      fileName: 'calvert-valux-park.jpg',
      displayName: 'Calvert Valux Park',
      description: '',
      date: '',
    },
    {
      fileName: 'cliques-2.jpg',
      displayName: 'Cliques',
      description: '',
      date: '',
    },
    {
      fileName: 'coney-broadwalk-on-a-friday-afternoon.jpg',
      displayName: 'Coney Island Broadwalk on a Friday Afternoon',
      description: '',
      date: '',
    },
    {
      fileName: 'curiosity.jpg',
      displayName: 'Curiosity',
      description: '',
      date: '',
    },
    {
      fileName: 'deserted-2.jpg',
      displayName: 'Deserted',
      description: '',
      date: '',
    },
    {
      fileName: 'deserted-3.jpg',
      displayName: 'Deserted',
      description: '',
      date: '',
    },
    {
      fileName: 'deserted-4.jpg',
      displayName: 'Deserted',
      description: '',
      date: '',
    },
    {
      fileName: 'deserted.jpg',
      displayName: 'Deserted',
      description: '',
      date: '',
    },
    {
      fileName: 'dollar-coffee.jpg',
      displayName: 'Dollar Coffee',
      description: '',
      date: '',
    },
    {
      fileName: 'duck.jpg',
      displayName: '',
      description: '',
      date: '',
    },
    {
      fileName: 'end-of-2025-2.jpg',
      displayName: 'End of 2025',
      description: '',
      date: '',
    },
    {
      fileName: 'european-landscape-1.jpg',
      displayName: 'European Landscape',
      description: '',
      date: '',
    },
    {
      fileName: 'european-landscape-2.jpg',
      displayName: 'European Landscape',
      description: '',
      date: '',
    },
    {
      fileName: 'exit-0.jpg',
      displayName: 'Exit',
      description: '',
      date: '',
    },
    {
      fileName: 'exit.jpg',
      displayName: 'Exit',
      description: '',
      date: '',
    },
    {
      fileName: 'field-closed.jpg',
      displayName: 'Field Closed',
      description: '',
      date: '',
    },
    {
      fileName: 'foreign.jpg',
      displayName: 'Foreign',
      description: '',
      date: '',
    },
    {
      fileName: 'intermission-2.jpg',
      displayName: 'Intermission',
      description: '',
      date: '',
    },
    {
      fileName: 'line-study-3.jpg',
      displayName: 'Line Study',
      description: '',
      date: '',
    },
    {
      fileName: 'line-study-4.jpg',
      displayName: 'Line Study',
      description: '',
      date: '',
    },
    {
      fileName: 'linger.jpg',
      displayName: 'Linger',
      description: '',
      date: '',
    },
    {
      fileName: 'lucid-dream-dec-2025.jpg',
      displayName: 'Lucid Dream',
      description: '',
      date: '',
    },
    {
      fileName: 'night-flowers-on-twin-peaks.jpg',
      displayName: 'Night Flowers on Twin Peaks',
      description: '',
      date: '',
    },
    {
      fileName: 'oblivion-and-company-3.jpg',
      displayName: 'Oblivion and Company',
      description: '',
      date: '',
    },
    {
      fileName: 'oblivion-and-self-company.jpg',
      displayName: 'Oblivion and Self Company',
      description: '',
      date: '',
    },
    {
      fileName: 'pampered.jpg',
      displayName: '',
      description: '',
      date: '',
    },
    {
      fileName: 'play-on-the-street-of-slush.jpg',
      displayName: '',
      description: '',
      date: '',
    },
    {
      fileName: 'portland-landscape-2.jpg',
      displayName: 'Portland Landscape',
      description: '',
      date: '',
    },
    {
      fileName: 'pre-ig.jpg',
      displayName: 'Pre-Instagram',
      description: '',
      date: '',
    },
    {
      fileName: 'private-property-2.jpg',
      displayName: 'Private Property',
      description: '',
      date: '',
    },
    {
      fileName: 'private-property.jpg',
      displayName: 'Private Property',
      description: '',
      date: '',
    },
    {
      fileName: 'quasi-curiosity.jpg',
      displayName: '',
      description: '',
      date: '',
    },
    {
      fileName: 'strangers.jpg',
      displayName: '',
      description: '',
      date: '',
    },
    {
      fileName: 'stretch.jpg',
      displayName: '',
      description: '',
      date: '',
    },
    {
      fileName: 'stroll-by-the-water-2.jpg',
      displayName: '',
      description: '',
      date: '',
    },
    {
      fileName: 'stroll-by-the-water.jpg',
      displayName: '',
      description: '',
      date: '',
    },
    {
      fileName: 'toms-coney-island-with-birb.jpg',
      displayName: 'Lingering in Tom\'s Coney Island',
      description: '',
      date: '',
    },
    {
      fileName: 'uncommon-place-1.jpg',
      displayName: 'Uncommon Place',
      description: '',
      date: '',
    },
    {
      fileName: 'wind-surfers-1.jpg',
      displayName: 'Wind Surfers',
      description: '',
      date: '',
    },
    {
      fileName: 'wind-surfers-2.jpg',
      displayName: 'Wind Surfers',
      description: '',
      date: '',
    },
    {
      fileName: 'window-shopper.jpg',
      displayName: 'Window Shopper',
      description: '',
      date: '',
    },
    {
      fileName: 'winter-in-calvert-valux-park-3.jpg',
      displayName: 'Winter in Calvert Valux Park',
      description: '',
      date: '',
    },
    {
      fileName: 'winter-in-calvert-valux-park-4.jpg',
      displayName: 'Winter in Calvert Valux Park',
      description: '',
      date: '',
    },
    {
      fileName: 'winter-in-calvert-valux-park-5.jpg',
      displayName: 'Winter in Calvert Valux Park',
      description: '',
      date: '',
    },
    {
      fileName: 'winter-retreat.jpg',
      displayName: 'Winter Retreat',
      description: '',
      date: '',
    },
    {
      fileName: 'world-and-cruise.jpg',
      displayName: 'World and Cruise',
      description: '',
      date: '',
    },
    
  ],
};

export default curatedWorks;
