import { ProgressStatus } from '../constants';

const showings = [
  // {
  //   fileName: '',
  //   displayName: '',
  //   description: '',
  //   date: '',
  // },
  {
    fileName: 'ma.jpg',
    displayName: '',
    description: '',
    date: '2014',
  },
  {
    fileName: 'people-and-lighthouse.jpg',
    displayName: 'People and Lighthouse',
    description: '',
    date: 'October 2023',
  },
  {
    fileName: 'early-friday-afternoon.jpg',
    displayName: 'Early Friday Afternoon',
    description: '',
    date: 'September 2024',
  },
  {
    fileName: 'intermission-3x2.jpg',
    displayName: 'Intermission',
    description: '',
    date: 'December 2025',
  },
  {
    fileName: 'city-bird.jpg',
    displayName: '',
    description: '',
    date: 'December 2025',
  },
  {
    fileName: 'pre-halloween-2025.jpg',
    displayName: '',
    description: '',
    date: 'October 2025',
  },
  {
    fileName: "child's-play.jpg",
    displayName: "Child's Play",
    description: '',
    date: 'December 2025',
  },
  {
    fileName: 'field-day-1.jpg',
    displayName: 'Field Day',
    description: '',
    date: 'December 2025',
  },
  {
    fileName: 'herder.jpg',
    displayName: 'Herder',
    description: '',
    date: 'December 2025',
  },
  {
    fileName: 'chrismas-2025.jpg',
    displayName: 'Christmas 2025',
    description: '',
    date: 'December 2025',
  },
  {
    fileName: 'winter-land.jpg',
    displayName: 'Winter Land',
    description: '',
    date: 'December 2025',
  },
  {
    fileName: 'winter-in-calvert-vaux-park.jpg',
    displayName: 'Winter in Calvert Vaux Park',
    description: '',
    date: 'December 2025',
  },
  {
    fileName: 'winter-in-calvert-vaux-park-2.jpg',
    displayName: 'Winter in Calvert Vaux Park',
    description: '',
    date: 'December 2025',
  },
  {
    fileName: 'color-study.jpg',
    displayName: 'Color Study',
    description: '',
    date: 'March 2024',
  },
  {
    fileName: 'urban-abstraction.jpg',
    displayName: 'Urban Abstraction',
    description: '',
    date: '',
  },
  {
    fileName: 'end-of-2025.jpg',
    displayName: 'End of 2025',
    description: '',
    date: '',
  },
  {
    fileName: 'beginning-of-2026.jpg',
    displayName: 'Beginning of 2026',
    description: '',
    date: 'January 2026',
  },
  {
    fileName: 'beginning-of-2026-1.jpg',
    displayName: 'Beginning of 2026',
    description: '',
    date: 'January 2026',
  },
  {
    fileName: 'wind-surfers.jpg',
    displayName: 'Wind Surfers',
    description: '',
    date: 'November 2025',
  },
  {
    fileName: 'early-morning-in-late-october.jpg',
    displayName: '',
    description: '',
    date: 'October 22nd, 2015',
  },
  {
    fileName: 'red-hook-red.jpg',
    displayName: 'Red Hook Red',
    description: '',
    date: '',
  },
  {
    fileName: 'red-hook-green.jpg',
    displayName: 'Red Hook Green',
    description: '',
    date: '',
  },
  {
    fileName: 'red-hook-water.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'mcdonals.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'fare-required.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'in-between-winter-and-spring.jpg',
    displayName: 'Between Winter and Spring',
    description: '',
    date: '',
  },
  {
    fileName: 'in-between-winter-and-spring-2.jpg',
    displayName: 'Between Winter and Spring',
    description: '',
    date: '',
  },
  {
    fileName: 'pinched.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'study-of-line.jpg',
    displayName: 'Line Study',
    description: '',
    date: 'November 2025',
  },
  {
    fileName: 'study-of-line-2.jpg',
    displayName: 'Line Study',
    description: '',
    date: 'November 2025',
  },
  {
    fileName: 'fish-head.jpg',
    displayName: '',
    description: '',
    date: '', // 'December 2025',
  },
  {
    fileName: 'painting-study-1.jpg',
    displayName: 'Photo Painting Study',
    description: '',
    date: '',
  },
  {
    fileName: 'painting-study-2.jpg',
    displayName: 'Photo Painting Study',
    description: '',
    date: '',
  },
  {
    fileName: 'painting-study-3.jpg',
    displayName: 'Photo Painting Study',
    description: '',
    date: 'December 2025',
  },
  {
    fileName: 'liminal-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'curiousity-o-playfulness.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'afternoon-stroll-with-company.jpg',
    displayName: 'Afternoon Stroll with Company',
    description: '',
    date: '',
  },
  {
    fileName: 'preyed.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'foot-prints-in-the-sand.jpg',
    displayName: 'Footprints in the Sand',
    description: '',
    date: '',
  },
  {
    fileName: 'winter-stock.jpg',
    displayName: 'Winter Stock',
    description: '',
    date: '',
  },
  {
    fileName: 'abandoned.jpg',
    displayName: 'Abandoned',
    description: '',
    date: '',
  },
  {
    fileName: 'accompany.jpg',
    displayName: 'Accompany',
    description: '',
    date: '',
  },
  {
    fileName: 'before-rainstorm-by-the-harbor.jpg',
    displayName: 'Before Rainstorm at the Harbor',
    description: '',
    date: '',
  },
  {
    fileName: 'beginning-of-2026-2.jpg',
    displayName: 'Beginning of 2026',
    description: '',
    date: '',
  },
  {
    fileName: 'beginning-of-2026-3.jpg',
    displayName: 'Beginning of 2026',
    description: '',
    date: '',
  },
  {
    fileName: 'brooklyn-bridge.jpg',
    displayName: 'Brooklyn Bridge',
    description: '',
    date: 'April 2024',
  },
  {
    fileName: 'bushuzhike.jpg',
    displayName: '不速之客',
    description: '',
    date: '',
  },
  {
    fileName: 'cajianerguo.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'calvert-valux-park.jpg',
    displayName: 'Calvert Valux Park',
    description: '',
    date: '',
  },
  {
    fileName: 'cliques-2.jpg',
    displayName: 'Cliques',
    description: '',
    date: '',
  },
  {
    fileName: 'coney-broadwalk-on-a-friday-afternoon.jpg',
    displayName: 'Coney Island Broadwalk on a Friday Afternoon',
    description: '',
    date: '',
  },
  {
    fileName: 'curiosity.jpg',
    displayName: 'Curiosity',
    description: '',
    date: '',
  },
  {
    fileName: 'deserted-2.jpg',
    displayName: 'Deserted',
    description: '',
    date: '',
  },
  {
    fileName: 'deserted-3.jpg',
    displayName: 'Deserted',
    description: '',
    date: '',
  },
  {
    fileName: 'deserted-4.jpg',
    displayName: 'Deserted',
    description: '',
    date: '',
  },
  {
    fileName: 'deserted.jpg',
    displayName: 'Deserted',
    description: '',
    date: '',
  },
  {
    fileName: 'dollar-coffee.jpg',
    displayName: 'Dollar Coffee',
    description: '',
    date: '',
  },
  {
    fileName: 'duck.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'end-of-2025-2.jpg',
    displayName: 'End of 2025',
    description: '',
    date: '',
  },
  {
    fileName: 'european-landscape-1.jpg',
    displayName: 'European Landscape',
    description: '',
    date: '',
  },
  {
    fileName: 'european-landscape-2.jpg',
    displayName: 'European Landscape',
    description: '',
    date: '',
  },
  {
    fileName: 'exit-0.jpg',
    displayName: 'Exit',
    description: '',
    date: '',
  },
  {
    fileName: 'exit.jpg',
    displayName: 'Exit',
    description: '',
    date: '',
  },
  {
    fileName: 'field-closed.jpg',
    displayName: 'Field Closed',
    description: '',
    date: '',
  },
  {
    fileName: 'foreign.jpg',
    displayName: 'Foreign',
    description: '',
    date: '',
  },
  {
    fileName: 'intermission-2.jpg',
    displayName: 'Intermission',
    description: '',
    date: '',
  },
  {
    fileName: 'line-study-3.jpg',
    displayName: 'Line Study',
    description: '',
    date: '',
  },
  {
    fileName: 'line-study-4.jpg',
    displayName: 'Line Study',
    description: '',
    date: '',
  },
  {
    fileName: 'linger.jpg',
    displayName: 'Linger',
    description: '',
    date: '',
  },
  {
    fileName: 'lucid-dream-dec-2025.jpg',
    displayName: 'Lucid Dream',
    description: '',
    date: '',
  },
  {
    fileName: 'night-flowers-on-twin-peaks.jpg',
    displayName: 'Night Flowers on Twin Peaks',
    description: '',
    date: '',
  },
  {
    fileName: 'oblivion-and-company-3.jpg',
    displayName: 'Oblivion and Company',
    description: '',
    date: '',
  },
  {
    fileName: 'oblivion-and-self-company.jpg',
    displayName: 'Oblivion and Self Company',
    description: '',
    date: '',
  },
  {
    fileName: 'pampered.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'play-on-the-street-of-slush.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'portland-landscape-2.jpg',
    displayName: 'Portland Landscape',
    description: '',
    date: '',
  },
  {
    fileName: 'pre-ig.jpg',
    displayName: 'Pre-Instagram',
    description: '',
    date: '',
  },
  {
    fileName: 'private-property-2.jpg',
    displayName: 'Private Property',
    description: '',
    date: '',
  },
  {
    fileName: 'private-property.jpg',
    displayName: 'Private Property',
    description: '',
    date: '',
  },
  {
    fileName: 'quasi-curiosity.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'strangers.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'stretch.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'stroll-by-the-water-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'stroll-by-the-water.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'toms-coney-island-with-birb.jpg',
    displayName: "Lingering in Tom's Coney Island",
    description: '',
    date: '',
  },
  {
    fileName: 'uncommon-place-1.jpg',
    displayName: 'Uncommon Place',
    description: '',
    date: '',
  },
  {
    fileName: 'wind-surfers-1.jpg',
    displayName: 'Wind Surfers',
    description: '',
    date: '',
  },
  {
    fileName: 'wind-surfers-2.jpg',
    displayName: 'Wind Surfers',
    description: '',
    date: '',
  },
  {
    fileName: 'window-shopper.jpg',
    displayName: 'Window Shopper',
    description: '',
    date: '',
  },
  {
    fileName: 'winter-in-calvert-valux-park-3.jpg',
    displayName: 'Winter in Calvert Valux Park',
    description: '',
    date: '',
  },
  {
    fileName: 'winter-in-calvert-valux-park-4.jpg',
    displayName: 'Winter in Calvert Valux Park',
    description: '',
    date: '',
  },
  {
    fileName: 'winter-in-calvert-valux-park-5.jpg',
    displayName: 'Winter in Calvert Valux Park',
    description: '',
    date: '',
  },
  {
    fileName: 'winter-retreat.jpg',
    displayName: 'Winter Retreat',
    description: '',
    date: '',
  },
  {
    fileName: 'world-and-cruise.jpg',
    displayName: 'World and Cruise',
    description: '',
    date: '2025',
  },
  {
    fileName: 'art.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'blasphemy.jpg',
    displayName: 'Blasphemy',
    description: '',
    date: '2018',
  },
  {
    fileName: 'blue-base.jpg',
    displayName: '',
    description: '',
    date: '2019',
  },
  {
    fileName: 'descending-glance.jpg',
    displayName: 'Descending Glance',
    description: '',
    date: 'June 2016',
  },
  {
    fileName: 'revealed.jpg',
    displayName: 'Revealed',
    description: '',
    date: 'June 2016',
  },
  {
    fileName: 'diety.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'duals.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'figure.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'figures.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'fluffy.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'hands-free.jpg',
    displayName: 'Hands Free',
    description: '',
    date: 'April 2015',
  },
  {
    fileName: 'hands-free-2.jpg',
    displayName: 'Hands Free',
    description: '',
    date: 'December 2016',
  },
  {
    fileName: 'jack-purcell.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'kit.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'liminal-0.jpg',
    displayName: 'Liminal',
    description: '',
    date: '',
  },
  {
    fileName: 'lisa-by-karen-kantuq.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'lisa-wip.jpg',
    displayName: 'WIP',
    description: '',
    date: '',
  },
  {
    fileName: 'sisyphus-and-lisa.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'modern-art.jpg',
    displayName: 'Modern Art',
    description: '',
    date: '',
  },
  {
    fileName: 'materials.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'minimal.jpg',
    displayName: '',
    description: '',
    date: 'July 2016',
  },
  {
    fileName: 'mjsokgb.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'new-museum.jpg',
    displayName: 'New Museum',
    description: '',
    date: '',
  },
  {
    fileName: 'nft-1.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'nft.jpg',
    displayName: 'NFT--Nice Fucking Tumbler',
    description: '',
    date: '',
  },
  {
    fileName: 'not-so-precarious.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'painting-1.jpg',
    displayName: 'Painting #0',
    description: '',
    date: '',
  },
  {
    fileName: 'pedestal-1.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'pedestal-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'persistence-of-memory.jpg',
    displayName: 'Persistence of Memory',
    description: '',
    date: '',
  },
  {
    fileName: 'precarious-ring.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'precarious.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'round-earth.jpg',
    displayName: '',
    description: '',
    date: 'April 2014',
  },
  {
    fileName: 'spray.jpg',
    displayName: '',
    description: '',
    date: 'April 2014',
  },
  {
    fileName: 'runtime-error.jpg',
    displayName: 'Runtime Error',
    description: '',
    date: 'October 2015',
  },
  {
    fileName: 'salvage.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'self-drawing-wall.jpg',
    displayName: '',
    description: '',
    date: '2020',
  },
  {
    fileName: 'skate-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'skate.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'skylight-pane.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'skylight.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'the-mezz.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'tools.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'ultraviolet.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'vans-jcrew.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'vc-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'vc.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'vd.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: '18068936959477316.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: '3.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: '33.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: '333.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: '4th-0.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: '4th-1.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: '4th-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'a-song-for-you-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'a-song-for-you-3.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'a-song-for-you-4.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'a-song-for-you-5.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'a-song-for-you.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'abandoned-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'accompany-0.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'alternate-rooms-by-the-sea.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'alternate-sharp-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'asters-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'asters.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'autumn-1.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'autumn-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'bar.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'be-on-the-look-out.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'beach-day-1.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'beach-day-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'beach-day.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'behind-the-wheels.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'bike.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'bits-and-pieces.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'bk-sky.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'blitz.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'blue-1.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'blue-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'boyi-chess-game.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'canadian-wild-fire.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'chops.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'chrismas-in-spring.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'chrismas-tree-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'chrismas-tree.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'city-within-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'city-within.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'claw-machines.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'cny-2024.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'coastal.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'color-study.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'composition-study-0002.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'composition-study-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'composition-study-3.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'composition-study-4.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'composition-study.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'cones-shakes-sundaes-for-all.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'coney-1.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'congregation-1.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'congregation.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'conservatory.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'convervatory-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'curse.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'daisies.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'dazed.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'dazed1.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'dazed2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'deserted-5.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'deserted.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'disco.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'disperse.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'dont-eat-soggy-waffle.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'double.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'echo.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'element-cloud.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'element-rust.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'element-sand.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'ellies-island.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'enter.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'entropy-1.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'entropy-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'entropy-3.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'exit-3.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'exit-4.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'exposed.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'exposure.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'fall-album.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'falling-water.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'field-day-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'first-snow.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'flat-iron.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'flee.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'flowers-for-new-year.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'flowers-for-new-year2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'flowers.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'fog.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'free.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'french-presses.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'fu.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'garden-of-memory-0.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'garden-of-memory-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'garden-of-memory-3.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'garden-of-memory.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'geometric.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'girl-in-dress-glitched-bw.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'girl-in-dress-glitched.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'glitch-1.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'glitch-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'glitch-3.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'glitch-4.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'glitch.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'glitched-1.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'glitched.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'god-love-my-home.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'guanyu.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'harvest-0001.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'harvest-0002.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'harvest.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'haste-0005.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'haste-1.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'haste-6.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'haste-side-b.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'hearts.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'heat.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'holiday-lights.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'hope-love-1.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'hope-love.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'hundertwasser.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'ice-cool.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'in-between-operating-season.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'industrial.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'installation-0.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'installation.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'kaleidoscope.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'keep-right-glitched.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'lavender.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'light-study-0002.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'light-study-0003.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'light-study-0004.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'light-study.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'line-and-light-study.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'line-study-0002.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'line-study0.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'loner.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'long-time-no-see.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'longing.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'love-n-live.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'lovers-cover.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'lovers.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'loves-in-the-air.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'low-hanging.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'lowfi.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'lucid-dream-1.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'lucid-dream-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'luck-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'luck.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'lunar.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'melted.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'mjsokgb-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'modern-art-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'moma-april-2024-1.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'moma-april-2024-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'moma-april-2024-3.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'moma-april-2024-4.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'more-life.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'moving-shadows-1.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'moving-shadows-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'night-carousel-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'night-carousel.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'no-thru-traffic.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'not-douboe-exposure.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'noticed.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'noticing.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'novelty.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'nutrient.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'nyc.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'oblivion-and-company-0000.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'oblivion-and-company-0001.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'omni-presence-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'omni-presence.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'on-duty-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'on-duty.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'one-world-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'one-world.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'outside-the-window-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'outside-the-window.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'parking.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'permanence.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'phins.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'portrait-study-0000.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'portrait-study-0001.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'portrait-study-0002.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'pot.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'pour-overs.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'primavera-o-verano-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'primavera-o-verano.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'private-property-0001.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'private-property-4.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'quarantined.jpg',
    displayName: 'Quarantined',
    description: '',
    date: '',
  },
  {
    fileName: 'queen-of-the-night-2.jpg',
    displayName: 'Queen of the Night',
    description: '',
    date: '',
  },
  {
    fileName: 'recharge.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'reflection-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'reflection-study-001.jpg',
    displayName: 'Reflection Study',
    description: '',
    date: '',
  },
  {
    fileName: 'reflection-study-1.jpg',
    displayName: 'Reflection Study with Lisa',
    description: '',
    date: '',
  },
  {
    fileName: 'reflection-study.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'reflection.jpg',
    displayName: 'Study with Lisa',
    description: '',
    date: '',
  },
  {
    fileName: 'reflective-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'reflective.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'rooms-by-the-sea-2.jpg',
    displayName: 'Rooms by the Sea II',
    description: '',
    date: '',
  },
  {
    fileName: 'scavengers.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'sculptural.jpg',
    displayName: 'Sculpture',
    description: '',
    date: '',
  },
  {
    fileName: 'sea-side.jpg',
    displayName: 'Sea Side',
    description: '',
    date: '',
  },
  {
    fileName: 'serenity-2.jpg',
    displayName: 'Serenity',
    description: '',
    date: '',
  },
  {
    fileName: 'serenity.jpg',
    displayName: 'Serenity',
    description: '',
    date: '',
  },
  {
    fileName: 'shadow-study.jpg',
    displayName: 'Shadow Study',
    description: '',
    date: '',
  },
  {
    fileName: 'shape-study-0002.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'shape-study-0003.jpg',
    displayName: 'Shadow Study',
    description: '',
    date: '',
  },
  {
    fileName: 'shape-study-0006.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'shape-study-0007.jpg',
    displayName: 'Shape and Composition Study',
    description: '',
    date: '',
  },
  {
    fileName: 'shape-study-0008.jpg',
    displayName: 'City Within',
    description: '',
    date: '',
  },
  {
    fileName: 'shape-study.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'sharp.jpg',
    displayName: 'Exposure',
    description: '',
    date: '',
  },
  {
    fileName: 'skylight-blue.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'skylight-gray.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'skylight-yellow.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'solitude.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'solo-show.jpg',
    displayName: 'Solo Show',
    description: '',
    date: '',
  },
  {
    fileName: 'spring-in-prospect-park.jpg',
    displayName: 'Spring in Prospect Park',
    description: '',
    date: '',
  },
  {
    fileName: 'spring-plum.jpg',
    displayName: 'Sign of Spring',
    description: '',
    date: '',
  },
  {
    fileName: 'standout.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'stay-on-walks.jpg',
    displayName: 'Stay on Walks',
    description: '',
    date: '',
  },
  {
    fileName: 'still.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'stool.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'stranded-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'stranded-3.jpg',
    displayName: 'Stranded',
    description: '',
    date: '',
  },
  {
    fileName: 'stroll-by-the-water-3.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'stroll-on-the-broadwalk.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'study-of-harmony-and-unity.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'summertime.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'tepid.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'test-flight.jpg',
    displayName: 'Test Flight',
    description: '',
    date: '',
  },
  {
    fileName: 'test-of-luck.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'time-and-light-study.jpg',
    displayName: 'Study with Lisa',
    description: '',
    date: '',
  },
  {
    fileName: 'time-study.jpg',
    displayName: 'Time Study',
    description: '',
    date: '',
  },
  {
    fileName: 'trick-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'trick-3.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'tricks-1.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'tricks.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'trio.jpg',
    displayName: 'Trio',
    description: '',
    date: '',
  },
  {
    fileName: 'una-mesa-para-dos.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'under-construction.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'under-the-cloud.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'urban.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'urban2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'victory-flower.jpg',
    displayName: 'Victory Flower',
    description: '',
    date: '',
  },
  {
    fileName: 'wall-self-drawing.jpg',
    displayName: 'Wall Self-Drawing',
    description: '',
    date: '',
  },
  {
    fileName: 'warm-flowers-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'warm-flowers.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'wave.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'west-facing-2.jpg',
    displayName: '',
    description: '',
    date: '',
  },
  {
    fileName: 'west-facing.jpg',
    displayName: '',
    description: '',
    date: '',
  },
];

const curatedWorks = {
  meta: {
    name: 'curatedWorks',
    displayName: 'From the Archive',
    about: '',
    detailedDescription: 'Updated regularly starting 2026',
    imageFolderName: 'curated-works',
    progressStatus: ProgressStatus.IN_PROGRESS,
    numberOfImages: showings.length,
    status: '',
    releaseStatus: '',
    releaseDate: '2010 - 9999',
    link: 'https://www.instagram.com/gr.xng/',
    linkDescription: '👁️‍🗨️@gr.xng',
  },
  showings,
};

export default curatedWorks;
